### ISSUE TITLE
[Command]: Add command `test`

### ISSUE THREAD

**Issue by lachlangro6** [nyx-team/nyx#3]
**Woozy Troll**
wzytroll

**Command Description, and Why it should be added**
Woozy is naughty, lets troll him

**Code for the Command**
sdv

**Comment by loldonut** [comment]
at least add an actual command request 🗿🗿🗿🗿

**Comment by loldonut** [comment]
Will add

**Comment by loldonut** [comment]
@GamingRoos we troll woozy through [snipe command](https://github.com/nyx-team/nyx/blob/main/legacy_commands/Fun/snipe.js)
